survos_bunny:
    api_key: '%env(BUNNY_API_KEY)%'
    storage_zone: museado-data-zip
    zones:
        -
            name: museado-data-zip
            id: 752027
            region: NY
            readonly_password: '%env(BUNNY_MUSEADO_DATA_ZIP_READONLY_PASSWORD)%'
            password: '%env(BUNNY_MUSEADO_DATA_ZIP_PASSWORD)%'
