framework:
    default_locale: en
    enabled_locales: ['en', 'es', 'hu'] # , 'de', 'hi', 'da'] # , 'fr', 'de', 'uk', 'hi', 'hu']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
